/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.cafi.salaodesktop.visao;

import bo.UsuarioBO;
import br.com.cafi.salaodesktop.modelo.entidades.Usuario;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ListarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ListarUsuario
     */
    private TelaInicial telaInicial;
    JInternalFrame jif;
    public ListarUsuario(TelaInicial telaInicial,JInternalFrame jif) {
        initComponents();
        carregarTabela();
        this.jif=jif;
        this.telaInicial=telaInicial;
    }

    private void carregarTabela() {
        removerTodasLinhas();
        UsuarioBO bo = new UsuarioBO();
        List<Usuario> lista = bo.findAll();
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        for (Usuario obj : lista) {
            model.addRow(new Object[]{obj.getId() + "",
                obj.getNome(), obj.getLogin()});
        }
    }

    private void removerTodasLinhas() {
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja remover?");
        if (opcao == JOptionPane.YES_OPTION) {
            DefaultTableModel model
                    = (DefaultTableModel) jTable1.getModel();
            int id = Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0) + "");
            UsuarioBO bo = new UsuarioBO();
            Usuario u = bo.getById(id);
            System.out.println("Tentando apagar o usuário " + u.getNome());
            bo.delete(u);
            
            carregarTabela();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model
                = (DefaultTableModel) jTable1.getModel();
        int id = Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0) + "");
        UsuarioBO bo = new UsuarioBO();
        Usuario u = bo.getById(id);
        //abrir novo internalframe, devido isso, precisamos do desktoppanel da 
        //tela inicial
        JInternalFrame jif = new JInternalFrame("Editar Usuário");
        jif.setBounds(0, 0, 400, 600);
        jif.setVisible(true);
        jif.setClosable(true);
        CadastrarUsuario cp = new CadastrarUsuario(jif,u);
        jif.add(cp);
        this.telaInicial.getDesktopPane().add(jif);
        this.jif.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
